// مكتبة التمارين: بيانات وصور من free-exercise-db (Public Domain / Unlicense).
// الصور في public/exercises/<id>/0.jpg و 1.jpg
export const MUSCLES = [
  { id: "chest", ar: "الصدر", en: "Chest" },
  { id: "back", ar: "الظهر", en: "Back" },
  { id: "shoulders", ar: "الكتف", en: "Shoulders" },
  { id: "traps", ar: "الترابيس", en: "Traps" },
  { id: "biceps", ar: "البايسبس", en: "Biceps" },
  { id: "triceps", ar: "الترايسبس", en: "Triceps" },
  { id: "forearms", ar: "الساعد", en: "Forearms" },
  { id: "abs", ar: "البطن", en: "Abs" },
  { id: "quads", ar: "الفخذ الأمامي", en: "Quads" },
  { id: "hamstrings", ar: "الفخذ الخلفي", en: "Hamstrings" },
  { id: "glutes", ar: "المؤخرة", en: "Glutes" },
  { id: "calves", ar: "السمانة", en: "Calves" },
];

export const EXERCISES = [
  { id: "Barbell_Bench_Press_-_Medium_Grip", muscle: "chest", ar: "بنش بريس بالبار", en: "Barbell Bench Press - Medium Grip", imgs: 2 },
  { id: "Dumbbell_Bench_Press", muscle: "chest", ar: "بنش بريس بالدمبل", en: "Dumbbell Bench Press", imgs: 2 },
  { id: "Barbell_Incline_Bench_Press_-_Medium_Grip", muscle: "chest", ar: "بنش مائل بالبار", en: "Barbell Incline Bench Press - Medium Grip", imgs: 2 },
  { id: "Incline_Dumbbell_Press", muscle: "chest", ar: "بنش مائل بالدمبل", en: "Incline Dumbbell Press", imgs: 2 },
  { id: "Dumbbell_Flyes", muscle: "chest", ar: "فلاي بالدمبل", en: "Dumbbell Flyes", imgs: 2 },
  { id: "Pushups", muscle: "chest", ar: "ضغط (بوش أب)", en: "Pushups", imgs: 2 },
  { id: "Decline_Barbell_Bench_Press", muscle: "chest", ar: "بنش منحدر بالبار", en: "Decline Barbell Bench Press", imgs: 2 },
  { id: "Machine_Bench_Press", muscle: "chest", ar: "بنش بريس ماكينة", en: "Machine Bench Press", imgs: 2 },
  { id: "Butterfly", muscle: "chest", ar: "باترفلاي (ماكينة)", en: "Butterfly", imgs: 2 },
  { id: "Dips_-_Chest_Version", muscle: "chest", ar: "متوازي للصدر", en: "Dips - Chest Version", imgs: 2 },
  { id: "Flat_Bench_Cable_Flyes", muscle: "chest", ar: "فلاي كيبل", en: "Flat Bench Cable Flyes", imgs: 2 },
  { id: "Wide-Grip_Lat_Pulldown", muscle: "back", ar: "سحب علوي واسع", en: "Wide-Grip Lat Pulldown", imgs: 2 },
  { id: "Close-Grip_Front_Lat_Pulldown", muscle: "back", ar: "سحب علوي ضيق", en: "Close-Grip Front Lat Pulldown", imgs: 2 },
  { id: "Pullups", muscle: "back", ar: "عقلة", en: "Pullups", imgs: 2 },
  { id: "Bent_Over_Barbell_Row", muscle: "back", ar: "تجديف بالبار", en: "Bent Over Barbell Row", imgs: 2 },
  { id: "Seated_Cable_Rows", muscle: "back", ar: "تجديف كيبل جالس", en: "Seated Cable Rows", imgs: 2 },
  { id: "One-Arm_Dumbbell_Row", muscle: "back", ar: "تجديف بالدمبل لذراع واحدة", en: "One-Arm Dumbbell Row", imgs: 2 },
  { id: "Barbell_Deadlift", muscle: "back", ar: "ديدلفت", en: "Barbell Deadlift", imgs: 2 },
  { id: "Hyperextensions_Back_Extensions", muscle: "back", ar: "تمديد أسفل الظهر", en: "Hyperextensions (Back Extensions)", imgs: 2 },
  { id: "Dumbbell_Shoulder_Press", muscle: "shoulders", ar: "ضغط كتف بالدمبل", en: "Dumbbell Shoulder Press", imgs: 2 },
  { id: "Standing_Military_Press", muscle: "shoulders", ar: "ضغط عسكري واقف", en: "Standing Military Press", imgs: 2 },
  { id: "Seated_Barbell_Military_Press", muscle: "shoulders", ar: "ضغط عسكري جالس", en: "Seated Barbell Military Press", imgs: 2 },
  { id: "Leverage_Shoulder_Press", muscle: "shoulders", ar: "ضغط كتف ماكينة", en: "Leverage Shoulder Press", imgs: 2 },
  { id: "Side_Lateral_Raise", muscle: "shoulders", ar: "رفرفة جانبية", en: "Side Lateral Raise", imgs: 2 },
  { id: "Cable_Seated_Lateral_Raise", muscle: "shoulders", ar: "رفرفة جانبية كيبل", en: "Cable Seated Lateral Raise", imgs: 2 },
  { id: "Front_Dumbbell_Raise", muscle: "shoulders", ar: "رفرفة أمامية", en: "Front Dumbbell Raise", imgs: 2 },
  { id: "Face_Pull", muscle: "shoulders", ar: "فيس بول", en: "Face Pull", imgs: 2 },
  { id: "Reverse_Flyes", muscle: "shoulders", ar: "رفرفة خلفية", en: "Reverse Flyes", imgs: 2 },
  { id: "Arnold_Dumbbell_Press", muscle: "shoulders", ar: "أرنولد برس", en: "Arnold Dumbbell Press", imgs: 2 },
  { id: "Barbell_Shrug", muscle: "traps", ar: "شراغ بالبار", en: "Barbell Shrug", imgs: 2 },
  { id: "Dumbbell_Shrug", muscle: "traps", ar: "شراغ بالدمبل", en: "Dumbbell Shrug", imgs: 2 },
  { id: "Cable_Shrugs", muscle: "traps", ar: "شراغ كيبل", en: "Cable Shrugs", imgs: 2 },
  { id: "Upright_Barbell_Row", muscle: "traps", ar: "سحب عمودي بالبار", en: "Upright Barbell Row", imgs: 2 },
  { id: "Barbell_Curl", muscle: "biceps", ar: "كيرل بالبار", en: "Barbell Curl", imgs: 2 },
  { id: "Dumbbell_Bicep_Curl", muscle: "biceps", ar: "كيرل بالدمبل", en: "Dumbbell Bicep Curl", imgs: 2 },
  { id: "Hammer_Curls", muscle: "biceps", ar: "كيرل هامر", en: "Hammer Curls", imgs: 2 },
  { id: "Concentration_Curls", muscle: "biceps", ar: "كيرل تركيز", en: "Concentration Curls", imgs: 2 },
  { id: "Preacher_Curl", muscle: "biceps", ar: "كيرل بريتشر", en: "Preacher Curl", imgs: 2 },
  { id: "Incline_Hammer_Curls", muscle: "biceps", ar: "كيرل هامر مائل", en: "Incline Hammer Curls", imgs: 2 },
  { id: "Cable_Hammer_Curls_-_Rope_Attachment", muscle: "biceps", ar: "كيرل هامر كيبل", en: "Cable Hammer Curls - Rope Attachment", imgs: 2 },
  { id: "Alternate_Incline_Dumbbell_Curl", muscle: "biceps", ar: "كيرل مائل بالتبادل", en: "Alternate Incline Dumbbell Curl", imgs: 2 },
  { id: "Triceps_Pushdown", muscle: "triceps", ar: "ضغط ترايسبس كيبل", en: "Triceps Pushdown", imgs: 2 },
  { id: "Triceps_Pushdown_-_Rope_Attachment", muscle: "triceps", ar: "ترايسبس حبل", en: "Triceps Pushdown - Rope Attachment", imgs: 2 },
  { id: "EZ-Bar_Skullcrusher", muscle: "triceps", ar: "سكل كراشر", en: "EZ-Bar Skullcrusher", imgs: 2 },
  { id: "Cable_Rope_Overhead_Triceps_Extension", muscle: "triceps", ar: "تمديد ترايسبس فوق الراس", en: "Cable Rope Overhead Triceps Extension", imgs: 2 },
  { id: "Dips_-_Triceps_Version", muscle: "triceps", ar: "متوازي للترايسبس", en: "Dips - Triceps Version", imgs: 2 },
  { id: "Bench_Dips", muscle: "triceps", ar: "ديبس على البنش", en: "Bench Dips", imgs: 2 },
  { id: "Close-Grip_Barbell_Bench_Press", muscle: "triceps", ar: "بنش ضيق", en: "Close-Grip Barbell Bench Press", imgs: 2 },
  { id: "Dumbbell_One-Arm_Triceps_Extension", muscle: "triceps", ar: "تمديد ترايسبس بالدمبل", en: "Dumbbell One-Arm Triceps Extension", imgs: 2 },
  { id: "Palms-Up_Barbell_Wrist_Curl_Over_A_Bench", muscle: "forearms", ar: "كيرل رسغ للأعلى", en: "Palms-Up Barbell Wrist Curl Over A Bench", imgs: 2 },
  { id: "Palms-Down_Wrist_Curl_Over_A_Bench", muscle: "forearms", ar: "كيرل رسغ للأسفل", en: "Palms-Down Wrist Curl Over A Bench", imgs: 2 },
  { id: "Cable_Wrist_Curl", muscle: "forearms", ar: "كيرل رسغ كيبل", en: "Cable Wrist Curl", imgs: 2 },
  { id: "Farmers_Walk", muscle: "forearms", ar: "مشي المزارع", en: "Farmer's Walk", imgs: 2 },
  { id: "Plank", muscle: "abs", ar: "بلانك", en: "Plank", imgs: 2 },
  { id: "Crunches", muscle: "abs", ar: "كرنش", en: "Crunches", imgs: 2 },
  { id: "Cable_Crunch", muscle: "abs", ar: "كرنش كيبل", en: "Cable Crunch", imgs: 2 },
  { id: "Hanging_Leg_Raise", muscle: "abs", ar: "رفع أرجل معلق", en: "Hanging Leg Raise", imgs: 2 },
  { id: "Flat_Bench_Lying_Leg_Raise", muscle: "abs", ar: "رفع أرجل على البنش", en: "Flat Bench Lying Leg Raise", imgs: 2 },
  { id: "Russian_Twist", muscle: "abs", ar: "التواء روسي", en: "Russian Twist", imgs: 2 },
  { id: "Ab_Crunch_Machine", muscle: "abs", ar: "كرنش ماكينة", en: "Ab Crunch Machine", imgs: 2 },
  { id: "Ab_Roller", muscle: "abs", ar: "عجلة البطن", en: "Ab Roller", imgs: 2 },
  { id: "Barbell_Squat", muscle: "quads", ar: "سكوات بالبار", en: "Barbell Squat", imgs: 2 },
  { id: "Barbell_Full_Squat", muscle: "quads", ar: "سكوات كامل", en: "Barbell Full Squat", imgs: 2 },
  { id: "Front_Barbell_Squat", muscle: "quads", ar: "سكوات أمامي", en: "Front Barbell Squat", imgs: 2 },
  { id: "Goblet_Squat", muscle: "quads", ar: "سكوات جوبلت", en: "Goblet Squat", imgs: 2 },
  { id: "Bodyweight_Squat", muscle: "quads", ar: "سكوات بوزن الجسم", en: "Bodyweight Squat", imgs: 2 },
  { id: "Leg_Press", muscle: "quads", ar: "ليج بريس", en: "Leg Press", imgs: 2 },
  { id: "Leg_Extensions", muscle: "quads", ar: "تمديد الأرجل", en: "Leg Extensions", imgs: 2 },
  { id: "Dumbbell_Lunges", muscle: "quads", ar: "لانجز بالدمبل", en: "Dumbbell Lunges", imgs: 2 },
  { id: "Barbell_Walking_Lunge", muscle: "quads", ar: "لانجز مشي بالبار", en: "Barbell Walking Lunge", imgs: 2 },
  { id: "Romanian_Deadlift", muscle: "hamstrings", ar: "ديدلفت روماني", en: "Romanian Deadlift", imgs: 2 },
  { id: "Stiff-Legged_Barbell_Deadlift", muscle: "hamstrings", ar: "ديدلفت أرجل مستقيمة", en: "Stiff-Legged Barbell Deadlift", imgs: 2 },
  { id: "Lying_Leg_Curls", muscle: "hamstrings", ar: "ليج كيرل نائم", en: "Lying Leg Curls", imgs: 2 },
  { id: "Seated_Leg_Curl", muscle: "hamstrings", ar: "ليج كيرل جالس", en: "Seated Leg Curl", imgs: 2 },
  { id: "Good_Morning", muscle: "hamstrings", ar: "جود مورنينج", en: "Good Morning", imgs: 2 },
  { id: "Glute_Ham_Raise", muscle: "hamstrings", ar: "رفع الفخذ الخلفي", en: "Glute Ham Raise", imgs: 2 },
  { id: "Barbell_Hip_Thrust", muscle: "glutes", ar: "هيب ثرست", en: "Barbell Hip Thrust", imgs: 2 },
  { id: "Barbell_Glute_Bridge", muscle: "glutes", ar: "جسر المؤخرة بالبار", en: "Barbell Glute Bridge", imgs: 2 },
  { id: "Glute_Kickback", muscle: "glutes", ar: "ركلة خلفية", en: "Glute Kickback", imgs: 2 },
  { id: "Butt_Lift_Bridge", muscle: "glutes", ar: "جسر المؤخرة", en: "Butt Lift (Bridge)", imgs: 2 },
  { id: "Standing_Calf_Raises", muscle: "calves", ar: "رفع السمانة واقف", en: "Standing Calf Raises", imgs: 2 },
  { id: "Seated_Calf_Raise", muscle: "calves", ar: "رفع السمانة جالس", en: "Seated Calf Raise", imgs: 2 },
  { id: "Calf_Press_On_The_Leg_Press_Machine", muscle: "calves", ar: "سمانة على ليج بريس", en: "Calf Press On The Leg Press Machine", imgs: 2 },
  { id: "Rocking_Standing_Calf_Raise", muscle: "calves", ar: "رفع سمانة واقف بالبار", en: "Rocking Standing Calf Raise", imgs: 2 },
  { id: "Donkey_Calf_Raises", muscle: "calves", ar: "رفع سمانة حمار", en: "Donkey Calf Raises", imgs: 2 },
];

export const exerciseImg = (id, i = 0) => `/exercises/${id}/${i}.jpg`;
export const findExercise = (id) => EXERCISES.find((e) => e.id === id);
