// قاعدة أطعمة مبدئية: سعودية/خليجية + أطعمة شائعة. القيم تقريبية لحصة وحدة.
// g = وزن الحصة بالجرام (تقريبي، مطبوخ). الحقول: id, ar (الاسم), en, unit (وصف الحصة), unitEn (serving in English), cal, p (بروتين), c (كارب), f (دهون)
export const FOODS = [
  { id: "kabsa-chicken", g: 450, ar: "كبسة دجاج", en: "Chicken kabsa", unit: "صحن", unitEn: "plate", cal: 750, p: 40, c: 95, f: 22 },
  { id: "kabsa-meat", g: 450, ar: "كبسة لحم", en: "Lamb kabsa", unit: "صحن", unitEn: "plate", cal: 850, p: 38, c: 95, f: 33 },
  { id: "mandi-chicken", g: 500, ar: "مندي دجاج", en: "Chicken mandi", unit: "ربع دجاجة مع رز", unitEn: "1/4 chicken with rice", cal: 800, p: 50, c: 90, f: 25 },
  { id: "mandi-meat", g: 450, ar: "مندي لحم", en: "Lamb mandi", unit: "صحن", unitEn: "plate", cal: 900, p: 45, c: 95, f: 35 },
  { id: "madghout", g: 450, ar: "مضغوط دجاج", en: "Chicken madghout", unit: "صحن", unitEn: "plate", cal: 780, p: 42, c: 92, f: 24 },
  { id: "jareesh", g: 350, ar: "جريش", en: "Jareesh", unit: "صحن", unitEn: "plate", cal: 450, p: 18, c: 62, f: 14 },
  { id: "margoog", g: 400, ar: "مرقوق", en: "Margoog", unit: "صحن", unitEn: "plate", cal: 520, p: 28, c: 58, f: 18 },
  { id: "saleeg", g: 400, ar: "سليق", en: "Saleeg", unit: "صحن", unitEn: "plate", cal: 600, p: 32, c: 75, f: 18 },
  { id: "shawarma-chicken", g: 250, ar: "شاورما دجاج", en: "Chicken shawarma", unit: "ساندويتش", unitEn: "sandwich", cal: 520, p: 30, c: 45, f: 24 },
  { id: "shawarma-meat", g: 250, ar: "شاورما لحم", en: "Beef shawarma", unit: "ساندويتش", unitEn: "sandwich", cal: 580, p: 28, c: 45, f: 30 },
  { id: "falafel", g: 220, ar: "فلافل", en: "Falafel sandwich", unit: "ساندويتش", unitEn: "sandwich", cal: 450, p: 14, c: 55, f: 20 },
  { id: "broast", g: 300, ar: "بروست", en: "Broasted chicken", unit: "قطعتين مع خبز", unitEn: "2 pieces with bread", cal: 650, p: 42, c: 30, f: 38 },
  { id: "burger", g: 220, ar: "برجر لحم", en: "Beef burger", unit: "ساندويتش", unitEn: "sandwich", cal: 550, p: 28, c: 40, f: 30 },
  { id: "fries", g: 117, ar: "بطاطس مقلية", en: "French fries", unit: "حصة وسط", unitEn: "medium serving", cal: 365, p: 4, c: 48, f: 17 },
  { id: "samosa", g: 50, ar: "سمبوسة", en: "Samosa", unit: "حبة", unitEn: "piece", cal: 150, p: 5, c: 14, f: 8 },
  { id: "foul", g: 250, ar: "فول", en: "Foul medames", unit: "صحن", unitEn: "plate", cal: 250, p: 15, c: 35, f: 6 },
  { id: "egg-boiled", g: 50, ar: "بيض مسلوق", en: "Boiled egg", unit: "حبة", unitEn: "piece", cal: 78, p: 6, c: 1, f: 5 },
  { id: "egg-fried", g: 46, ar: "بيض مقلي", en: "Fried egg", unit: "حبة", unitEn: "piece", cal: 95, p: 6, c: 1, f: 7 },
  { id: "bread-arabic", g: 60, ar: "خبز عربي", en: "Arabic bread", unit: "رغيف", unitEn: "loaf", cal: 170, p: 6, c: 33, f: 1 },
  { id: "bread-tannour", g: 100, ar: "خبز تنور", en: "Tannour bread", unit: "رغيف", unitEn: "loaf", cal: 250, p: 8, c: 50, f: 2 },
  { id: "rice", g: 158, ar: "رز أبيض", en: "White rice", unit: "كوب مطبوخ", unitEn: "cup, cooked", cal: 205, p: 4, c: 45, f: 0.4 },
  { id: "chicken-breast", g: 100, ar: "صدر دجاج مشوي", en: "Grilled chicken breast", unit: "100 جم", unitEn: "100 g", cal: 165, p: 31, c: 0, f: 4 },
  { id: "chicken-thigh", g: 100, ar: "فخذ دجاج مشوي (بدون جلد)", en: "Grilled chicken thigh (skinless)", unit: "100 جم", unitEn: "100 g", cal: 209, p: 26, c: 0, f: 11 },
  { id: "chicken-thigh-skin", g: 100, ar: "فخذ دجاج مشوي (بالجلد)", en: "Grilled chicken thigh (with skin)", unit: "100 جم", unitEn: "100 g", cal: 247, p: 24, c: 0, f: 16 },
  { id: "chicken-wings", g: 100, ar: "أجنحة دجاج مشوية", en: "Roasted chicken wings", unit: "100 جم", unitEn: "100 g", cal: 290, p: 27, c: 0, f: 20 },
  { id: "chicken-boiled", g: 100, ar: "دجاج مسلوق", en: "Boiled chicken", unit: "100 جم", unitEn: "100 g", cal: 195, p: 27, c: 0, f: 9 },
  { id: "chicken-fried", g: 100, ar: "دجاج مقلي / بروستد", en: "Fried / broasted chicken", unit: "100 جم", unitEn: "100 g", cal: 260, p: 21, c: 10, f: 15 },
  { id: "lamb-cooked", g: 100, ar: "لحم غنم مطبوخ", en: "Cooked lamb", unit: "100 جم", unitEn: "100 g", cal: 280, p: 25, c: 0, f: 19 },
  { id: "rice-kabsa", g: 100, ar: "رز كبسة", en: "Kabsa rice", unit: "100 جم", unitEn: "100 g", cal: 170, p: 3.5, c: 29, f: 4.5 },
  { id: "rice-mandi", g: 100, ar: "رز مندي", en: "Mandi rice", unit: "100 جم", unitEn: "100 g", cal: 160, p: 3, c: 30, f: 3 },
  { id: "steak", g: 100, ar: "ستيك لحم مشوي", en: "Grilled steak", unit: "100 جم", unitEn: "100 g", cal: 250, p: 26, c: 0, f: 15 },
  { id: "fish", g: 100, ar: "سمك مشوي", en: "Grilled fish", unit: "100 جم", unitEn: "100 g", cal: 140, p: 24, c: 0, f: 4 },
  { id: "oats", g: 234, ar: "شوفان", en: "Oatmeal", unit: "كوب مطبوخ", unitEn: "cup, cooked", cal: 160, p: 6, c: 27, f: 3 },
  { id: "whey", g: 30, ar: "بروتين شيك (واي)", en: "Whey protein", unit: "سكوب", unitEn: "scoop", cal: 120, p: 24, c: 3, f: 1.5 },
  { id: "peanut-butter", g: 16, ar: "زبدة فول سوداني", en: "Peanut butter", unit: "ملعقة كبيرة", unitEn: "tablespoon", cal: 95, p: 4, c: 3, f: 8 },
  { id: "dates", g: 8, ar: "تمر", en: "Dates", unit: "حبة", unitEn: "piece", cal: 25, p: 0.2, c: 6.5, f: 0 },
  { id: "banana", g: 118, ar: "موز", en: "Banana", unit: "حبة", unitEn: "piece", cal: 105, p: 1.3, c: 27, f: 0.4 },
  { id: "apple", g: 182, ar: "تفاح", en: "Apple", unit: "حبة", unitEn: "piece", cal: 95, p: 0.5, c: 25, f: 0.3 },
  { id: "milk", g: 244, ar: "حليب كامل الدسم", en: "Whole milk", unit: "كوب", unitEn: "cup", cal: 150, p: 8, c: 12, f: 8 },
  { id: "laban", g: 245, ar: "لبن", en: "Laban (buttermilk)", unit: "كوب", unitEn: "cup", cal: 100, p: 6, c: 8, f: 4 },
  { id: "yogurt", g: 245, ar: "زبادي", en: "Yogurt", unit: "كوب", unitEn: "cup", cal: 120, p: 8, c: 9, f: 5 },
  { id: "arabic-coffee", g: 50, ar: "قهوة عربية", en: "Arabic coffee", unit: "فنجان", unitEn: "small cup (finjan)", cal: 5, p: 0, c: 1, f: 0 },
  { id: "tea-sugar", g: 240, ar: "شاي بسكر", en: "Sweet tea", unit: "كوب", unitEn: "cup", cal: 40, p: 0, c: 10, f: 0 },
  { id: "orange-juice", g: 248, ar: "عصير برتقال", en: "Orange juice", unit: "كوب", unitEn: "cup", cal: 110, p: 2, c: 26, f: 0.5 },
  { id: "kunafa", g: 150, ar: "كنافة", en: "Kunafa", unit: "قطعة", unitEn: "piece", cal: 350, p: 7, c: 40, f: 18 },
  { id: "luqaimat", g: 100, ar: "لقيمات", en: "Luqaimat", unit: "5 حبات", unitEn: "5 pieces", cal: 280, p: 3, c: 40, f: 12 },
];
