// قاعدة أطعمة مبدئية: سعودية/خليجية + أطعمة شائعة. القيم تقريبية لحصة وحدة.
// الحقول: id, ar (الاسم), en, unit (وصف الحصة), cal, p (بروتين), c (كارب), f (دهون)
export const FOODS = [
  { id: "kabsa-chicken", ar: "كبسة دجاج", en: "Chicken kabsa", unit: "صحن", cal: 750, p: 40, c: 95, f: 22 },
  { id: "kabsa-meat", ar: "كبسة لحم", en: "Lamb kabsa", unit: "صحن", cal: 850, p: 38, c: 95, f: 33 },
  { id: "mandi-chicken", ar: "مندي دجاج", en: "Chicken mandi", unit: "ربع دجاجة مع رز", cal: 800, p: 50, c: 90, f: 25 },
  { id: "mandi-meat", ar: "مندي لحم", en: "Lamb mandi", unit: "صحن", cal: 900, p: 45, c: 95, f: 35 },
  { id: "madghout", ar: "مضغوط دجاج", en: "Chicken madghout", unit: "صحن", cal: 780, p: 42, c: 92, f: 24 },
  { id: "jareesh", ar: "جريش", en: "Jareesh", unit: "صحن", cal: 450, p: 18, c: 62, f: 14 },
  { id: "margoog", ar: "مرقوق", en: "Margoog", unit: "صحن", cal: 520, p: 28, c: 58, f: 18 },
  { id: "saleeg", ar: "سليق", en: "Saleeg", unit: "صحن", cal: 600, p: 32, c: 75, f: 18 },
  { id: "shawarma-chicken", ar: "شاورما دجاج", en: "Chicken shawarma", unit: "ساندويتش", cal: 520, p: 30, c: 45, f: 24 },
  { id: "shawarma-meat", ar: "شاورما لحم", en: "Beef shawarma", unit: "ساندويتش", cal: 580, p: 28, c: 45, f: 30 },
  { id: "falafel", ar: "فلافل", en: "Falafel sandwich", unit: "ساندويتش", cal: 450, p: 14, c: 55, f: 20 },
  { id: "broast", ar: "بروست", en: "Broasted chicken", unit: "قطعتين مع خبز", cal: 650, p: 42, c: 30, f: 38 },
  { id: "burger", ar: "برجر لحم", en: "Beef burger", unit: "ساندويتش", cal: 550, p: 28, c: 40, f: 30 },
  { id: "fries", ar: "بطاطس مقلية", en: "French fries", unit: "حصة وسط", cal: 365, p: 4, c: 48, f: 17 },
  { id: "samosa", ar: "سمبوسة", en: "Samosa", unit: "حبة", cal: 150, p: 5, c: 14, f: 8 },
  { id: "foul", ar: "فول", en: "Foul medames", unit: "صحن", cal: 250, p: 15, c: 35, f: 6 },
  { id: "egg-boiled", ar: "بيض مسلوق", en: "Boiled egg", unit: "حبة", cal: 78, p: 6, c: 1, f: 5 },
  { id: "egg-fried", ar: "بيض مقلي", en: "Fried egg", unit: "حبة", cal: 95, p: 6, c: 1, f: 7 },
  { id: "bread-arabic", ar: "خبز عربي", en: "Arabic bread", unit: "رغيف", cal: 170, p: 6, c: 33, f: 1 },
  { id: "bread-tannour", ar: "خبز تنور", en: "Tannour bread", unit: "رغيف", cal: 250, p: 8, c: 50, f: 2 },
  { id: "rice", ar: "رز أبيض", en: "White rice", unit: "كوب مطبوخ", cal: 205, p: 4, c: 45, f: 0.4 },
  { id: "chicken-breast", ar: "صدر دجاج مشوي", en: "Grilled chicken breast", unit: "100 جم", cal: 165, p: 31, c: 0, f: 4 },
  { id: "steak", ar: "ستيك لحم مشوي", en: "Grilled steak", unit: "100 جم", cal: 250, p: 26, c: 0, f: 15 },
  { id: "fish", ar: "سمك مشوي", en: "Grilled fish", unit: "100 جم", cal: 140, p: 24, c: 0, f: 4 },
  { id: "oats", ar: "شوفان", en: "Oatmeal", unit: "كوب مطبوخ", cal: 160, p: 6, c: 27, f: 3 },
  { id: "whey", ar: "بروتين شيك (واي)", en: "Whey protein", unit: "سكوب", cal: 120, p: 24, c: 3, f: 1.5 },
  { id: "peanut-butter", ar: "زبدة فول سوداني", en: "Peanut butter", unit: "ملعقة كبيرة", cal: 95, p: 4, c: 3, f: 8 },
  { id: "dates", ar: "تمر", en: "Dates", unit: "حبة", cal: 25, p: 0.2, c: 6.5, f: 0 },
  { id: "banana", ar: "موز", en: "Banana", unit: "حبة", cal: 105, p: 1.3, c: 27, f: 0.4 },
  { id: "apple", ar: "تفاح", en: "Apple", unit: "حبة", cal: 95, p: 0.5, c: 25, f: 0.3 },
  { id: "milk", ar: "حليب كامل الدسم", en: "Whole milk", unit: "كوب", cal: 150, p: 8, c: 12, f: 8 },
  { id: "laban", ar: "لبن", en: "Laban (buttermilk)", unit: "كوب", cal: 100, p: 6, c: 8, f: 4 },
  { id: "yogurt", ar: "زبادي", en: "Yogurt", unit: "كوب", cal: 120, p: 8, c: 9, f: 5 },
  { id: "arabic-coffee", ar: "قهوة عربية", en: "Arabic coffee", unit: "فنجان", cal: 5, p: 0, c: 1, f: 0 },
  { id: "tea-sugar", ar: "شاي بسكر", en: "Sweet tea", unit: "كوب", cal: 40, p: 0, c: 10, f: 0 },
  { id: "orange-juice", ar: "عصير برتقال", en: "Orange juice", unit: "كوب", cal: 110, p: 2, c: 26, f: 0.5 },
  { id: "kunafa", ar: "كنافة", en: "Kunafa", unit: "قطعة", cal: 350, p: 7, c: 40, f: 18 },
  { id: "luqaimat", ar: "لقيمات", en: "Luqaimat", unit: "5 حبات", cal: 280, p: 3, c: 40, f: 12 },
];